### ISSUE TITLE
<tempDirectory> is relative to ${project.build.directory}

### ISSUE THREAD

**Issue by lilalinda** [techatspree/maven-latex-plugin#2]
This is not much of an issue just needs a slight correction in your "Configuration" page (http://akquinet.github.com/maven-latex-plugin/configuration.html).  If you specify `<tempDirectory>` in your settings, the path is always relative to `${project.build.directory}` so in the example of the default configuration, I would change:

```
        <!-- the working directory, for temporary files and LaTeX processing -->
        <tempDirectory>${project.build.directory}/m2latex</tempDirectory>
```

to

```
        <!-- the working directory, for temporary files and LaTeX processing; relative to ${project.build.directory} -->
        <tempDirectory>m2latex</tempDirectory>
```

Hope this helps,
Linda

**Comment by cerker** [comment]
Linda, 

I changed exactly this for the current release because of security reasons, to prevent something like the the /usr directory when the plugin is misconfigured.

It seems I forgot to change the documentation.

Thanks for pointing to it, I will adopt the configuration page...

**Comment by lilalinda** [comment]
Good.  I'm glad you are reading the issues, as I would like to get my other one resolved (multiple executions)...

I'm using this in my first Maven project, and was so happy to find a plugin that suits my needs.  Thanks, also, for making everything available online, so that I could actually browse the code and learn about the LaTeX plugin as well as Maven itself...

**Comment by cerker** [comment]
Updated the configuration page to show the proper information as proposed by lilalinda.
