### ISSUE TITLE
Biblatex Support?

### ISSUE THREAD

**Issue by hschoefer** [techatspree/maven-latex-plugin#3]
Is there any possibility to add support for Biblatex?
I added it last year and can't send my modification to you. I didn't found any mail address to contact you.

With my modification "makeindex" is also called. Some method checks if "Writing glossary file " + texFile + ".glo" string is written in glo file. If this string exists another method calls "makeindex" with parameter.

That's all you need to add Biblatex support.

**Comment by cerker** [comment]
Hi, that's great news! 

Today I'll write some step-by-step documentation how to contribute via GitHub - basically it will include forking the project to your GitHub repo, cloning it to your local machine, creating a branch, commit the changes, pushing them to your GitHub repo and creating a pull request.

This may sound more complicated as it actually is. Actually it's pretty straight forward.

Thanks a lot for contributing your code!

**Comment by cerker** [comment]
Please consult the following wiki page for more detailed instructions on how to provide your code:

https://github.com/akquinet/maven-latex-plugin/wiki/Contribute

If there are any questions, just ask...

**Comment by hschoefer** [comment]
Thanks for that instructions.
I have a huge problem. In middle of February I got a HDD crash and I lost a much of work which was created before. In addition my backup got damaged, too. Now the additional source code for the maven latex plugin is lost. That's very frustrating! Sry. :(

**Comment by cerker** [comment]
That's sad news. Do you think you can get the code back? Do you intend rewriting it?

**Comment by hschoefer** [comment]
Yes, I prepared first steps to rebuild this things.
Do you have any source code formating template for Eclipse?

Is there any possibility to send a private message to you?
